export const agentData = [
  {
    color:"rgb(194, 9, 227)",
    type: "CONTROLLER",
    typeIcon: require("../assets/ASTRA/AgentType.png"),
    name: "ASTRA",
    emoticon: require("../assets/ASTRA/emoticon.png"),
    wallpaper: require("../assets/ASTRA/Wallpaper.jpg"),
    description: "Ghanaian Agent Astra harnesses the energies of the cosmos to reshape battlefields to her whim. With full command of her astral form and a talent for deep strategic foresight, she’s always eons ahead of her enemy’s next move.",
    one: require("../assets/ASTRA/one.png"),
    oneDescription: `Gravity Well is Astra's crowd control ability that pulls agents toward its center when activated. It disrupts positioning and can interrupt spike defusals by dragging players out of range. Agents can resist the pull by moving away, but timing is key to counter it.`,
    two: require("../assets/ASTRA/two.png"),
    twoDescription: "ACTIVATE a Star to detonate a Nova Pulse. The Nova Pulse charges briefly then strikes, Concussing all players in its area.",
    three: require("../assets/ASTRA/three.png"),
    threeDescription: `ACTIVATE a  Star to transform it into a Nebula (smoke). USE a Star to Dissipate it, returning the Star to be placed in a new location after a delay. Dissipate briefly forms a fake Nebula at the Star's location before returning.`,
    ult: require("../assets/ASTRA/ult.png"),
    ultDescription: "When Cosmic Divide is charged, use ALT FIRE in Astral Form to begin aiming it, then FIRE to select two locations. An infinite Cosmic Divide connects the two points you select. Cosmic Divide blocks bullets and sound.",},
  {
    color:"rgb(223, 22, 4)",
    type: "CONTROLLER",
    typeIcon: require("../assets/BRIMSTONE/AgentType.png"),
    name: "BRIMSTONE",
    emoticon: require("../assets/BRIMSTONE/emoticon.png"),
    wallpaper: require("../assets/BRIMSTONE/Wallpaper.jpg"),
    description: "Joining from the U.S.A., Brimstone's orbital arsenal ensures his squad always has the advantage. His ability to deliver utility precisely and from a distance make him an unmatched boots-on-the-ground commander.",
    one: require("../assets/BRIMSTONE/one.png"),
    oneDescription: "EQUIP an incendiary grenade launcher. FIRE to launch a grenade that detonates as it comes to a rest on the floor, creating a lingering fire zone that damages players within the zone.",
    two: require("../assets/BRIMSTONE/two.png"),
    twoDescription: "INSTANTLY toss down a stim beacon. Upon landing, it creates a field that grants players a Combat Stim and a Speed Boost.",
    three: require("../assets/BRIMSTONE/three.png"),
    threeDescription: "EQUIP a tactical map. FIRE to set locations where Brimstone's smoke clouds will land. ALT FIRE to confirm, launching long-lasting smoke clouds that block vision in the selected area.",
    ult: require("../assets/BRIMSTONE/ult.png"),
    ultDescription: "EQUIP a tactical map. FIRE to launch a lingering orbital strike laser at the selected location, dealing high damage-over-time to players caught in the selected area.",},
  {
    color:"rgb(164, 9, 148)",
    type: "CONTROLLER",
    typeIcon: require("../assets/CLOVE/AgentType.png"),
    name: "CLOVE",
    emoticon: require("../assets/CLOVE/emoticon.png"),
    wallpaper: require("../assets/CLOVE/Wallpaper.jpg"),
    description: "Scottish troublemaker Clove makes mischief for enemies in both the heat of combat and the cold of death. The young immortal keeps foes guessing, even from beyond the grave, their return to the living only ever a moment away.",
    one: require("../assets/CLOVE/one.png"),
    oneDescription: "ACTIVATE to absorb the life force of a fallen enemy that Clove damaged or killed, gaining haste and temporary health.",
    two: require("../assets/CLOVE/two.png"),
    twoDescription: "EQUIP a fragment of immortality essence. FIRE to throw the fragment, which upon landing on the floor, erupts after a short delay and temporarily Decays all targets caught inside.",
    three: require("../assets/CLOVE/three.png"),
    threeDescription: "EQUIP a view of the battlefield. FIRE to set the locations where Clove's clouds will settle. ALT FIRE to confirm, launching clouds that block vision in the chosen areas. Clove can use this ability after death.",
    ult: require("../assets/CLOVE/ult.png"),
    ultDescription: "After dying, ACTIVATE to resurrect. Once resurrected, Clove must earn a kill or a damaging assist within a set time or they will die. REACTIVATE to cancel early.",},
  {
    color:"rgb(3, 86, 150)",
    type: "CONTROLLER",
    typeIcon: require("../assets/HARBOR/AgentType.png"),
    name: "HARBOR",
    emoticon: require("../assets/HARBOR/emoticon.png"),
    wallpaper: require("../assets/HARBOR/Wallpaper.png"),
    description: "Hailing from India's coast, Harbor storms the field wielding ancient technology with dominion over water. He unleashes frothing rapids and crushing waves to shield his allies, or pummel those that oppose him.",
    one: require("../assets/HARBOR/one.png"),
    oneDescription: "EQUIP a wave of water. FIRE to send the wave rolling forward and through walls. RE-USE to stop the wave. Players hit are Slowed.",
    two: require("../assets/HARBOR/two.png"),
    twoDescription: "EQUIP a sphere of shielding water. FIRE to throw. ALT FIRE to lob. Upon impacting the ground, spawn a destructible water shield that blocks bullets.",
    three: require("../assets/HARBOR/three.png"),
    threeDescription: "EQUIP a wall of water. FIRE to send the water forward along the ground. HOLD FIRE to guide the water in the direction of your crosshair, passing through the world, spawning a wall along the water's path. ALT FIRE while bending to stop the water early. Players hit are Slowed.",
    ult: require("../assets/HARBOR/ult.png"),
    ultDescription: "EQUIP the full power of your Artifact. FIRE to summon a geyser pool on the ground. Enemy players in the area are targeted by successive geyser strikes. Players caught within a strike are Concussed.",},
  {
    color:"rgb(5, 1, 94)",
    type: "CONTROLLER",
    typeIcon: require("../assets/OMEN/AgentType.png"),
    name: "OMEN",
    emoticon: require("../assets/OMEN/emoticon.png"),
    wallpaper: require("../assets/OMEN/Wallpaper.jpg"),
    description: "A phantom of a memory, Omen hunts in the shadows. He renders enemies blind, teleports across the field, then lets paranoia take hold as his foe scrambles to learn where he might strike next.",
    one: require("../assets/OMEN/one.png"),
    oneDescription: "EQUIP a shrouded step ability and see its range indicator. FIRE to begin a brief channel, then teleport to the marked location.",
    two: require("../assets/OMEN/two.png"),
    twoDescription: "EQUIP a blinding orb. FIRE to throw it forward, briefly Nearsighting and Deafening all players it touches. This projectile can pass straight through walls.",
    three: require("../assets/OMEN/three.png"),
    threeDescription: "EQUIP a shadow orb, entering a phased world to place and target the orbs. PRESS the ability key to throw the shadow orb to the marked location, creating a long-lasting shadow sphere that blocks vision. HOLD FIRE while targeting to move the marker further away. HOLD ALT FIRE while targeting to move the marker closer. PRESS RELOAD to toggle normal targeting view.",
    ult: require("../assets/OMEN/ult.png"),
    ultDescription: "EQUIP a tactical map. FIRE to begin teleporting to the selected location. While teleporting, Omen will appear as a Shade that can be destroyed by an enemy to cancel his teleport, or PRESS EQUIP for Omen to cancel his teleport.",},
  {
    color:"rgb(29, 180, 84)",
    type: "CONTROLLER",
    typeIcon: require("../assets/VIPER/AgentType.png"),
    name: "VIPER",
    emoticon: require("../assets/VIPER/emoticon.png"),
    wallpaper: require("../assets/VIPER/Wallpaper.jpg"),
    description: "The American chemist, Viper deploys an array of poisonous chemical devices to control the battlefield and choke the enemy's vision. If the toxins don't kill her prey, her mind games surely will.",
    one: require("../assets/VIPER/one.png"),
    oneDescription: "EQUIP a chemical launcher. FIRE to launch a canister that shatters upon hitting the floor, creating a lingering chemical zone that damages and applies Vulnerable.",
    two: require("../assets/VIPER/two.png"),
    twoDescription: "EQUIP a gas emitter. FIRE to throw the emitter that perpetually remains throughout the round. ALT FIRE to lob. RE-USE the ability to create a toxic gas cloud at the cost of fuel. This ability can be picked up to be REDEPLOYED before the round starts and can be RE-USED more than once throughout the round.",
    three: require("../assets/VIPER/three.png"),
    threeDescription: "EQUIP a gas emitter launcher that penetrates terrain. FIRE to deploy a long line of gas emitters. RE-USE the ability to create a tall wall of toxic gas at the cost of fuel. This ability can be RE-USED more than once.",
    ult: require("../assets/VIPER/ult.png"),
    ultDescription: "EQUIP a chemical sprayer. FIRE to spray a chemical cloud in all directions around Viper, creating a large cloud that Nearsights players and Decays the health of enemies inside of it. HOLD the ability key to disperse the cloud early.",},
  {
    color:"rgb(223, 138, 21)",
    type: "INITIATOR",
    typeIcon: require("../assets/BREACH/AgentType.png"),
    name: "BREACH",
    emoticon: require("../assets/BREACH/emoticon.png"),
    wallpaper: require("../assets/BREACH/Wallpaper.jpg"),
    description: "Breach, the bionic Swede, fires powerful, targeted kinetic blasts to aggressively clear a path through enemy ground. The damage and disruption he inflicts ensures no fight is ever fair.",
    one: require("../assets/BREACH/one.png"),
    oneDescription: "EQUIP a fusion charge. FIRE the charge to set a slow-acting burst through the wall. The burst does heavy damage to anyone caught in its area.",
    two: require("../assets/BREACH/two.png"),
    twoDescription: "EQUIP a blinding charge. FIRE the charge to set a fast-acting burst through the wall. The charge detonates to Blind all players looking at it.",
    three: require("../assets/BREACH/three.png"),
    threeDescription: "EQUIP a seismic blast. HOLD FIRE to increase the distance. RELEASE to set off the quake, Concussing all players in its zone and in a line up to the zone.",
    ult: require("../assets/BREACH/ult.png"),
    ultDescription: "EQUIP a Seismic Charge. FIRE to send a cascading quake through all terrain in a large zone. The quake Concusses and knocks up anyone caught in it.",},
  {
    color:"rgba(159, 7, 7, 0.74)",
    type: "INITIATOR",
    typeIcon: require("../assets/FADE/AgentType.png"),
    name: "FADE",
    emoticon: require("../assets/FADE/emoticon.png"),
    wallpaper: require("../assets/FADE/Wallpaper.jpg"),
    description: "Turkish bounty hunter Fade unleashes the power of raw nightmare to seize enemy secrets. Attuned with terror itself, she hunts down targets and reveals their deepest fears - before crushing them in the dark.",
    one: require("../assets/FADE/one.png"),
    oneDescription: "EQUIP a prowler. FIRE to send the prowler forward. HOLD FIRE to steer the prowler towards your crosshair. The prowler will chase down the first enemy or terror trail it sees, and Nearsight the enemy on impact.",
    two: require("../assets/FADE/two.png"),
    twoDescription: "EQUIP a knot of raw fear. FIRE to throw. The knot drops down after a set time. RE-USE to drop the knot early. The knot ruptures on impact, holding nearby enemies in place. Held enemies are Deafened, and Decayed.",
    three: require("../assets/FADE/three.png"),
    threeDescription: "EQUIP a haunting watcher. FIRE to throw. The watcher drops down after a set time. RE-USE to drop the watcher early. The watcher lashes out on impact, Revealing enemies in its line of sight and creating terror trails to them. Enemies can destroy the watcher.",
    ult: require("../assets/FADE/ult.png"),
    ultDescription: "EQUIP the power of nightmare itself. FIRE to unleash a wave of unstoppable nightmare energy. Enemies caught in the wave are Marked by terror trails, Deafened, and Decayed.",},
  {
    color:"rgb(223, 234, 5)",
    type: "INITIATOR",
    typeIcon: require("../assets/GEKKO/AgentType.png"),
    name: "GEKKO",
    emoticon: require("../assets/GEKKO/emoticon.png"),
    wallpaper: require("../assets/GEKKO/Wallpaper.jpg"),
    description: "Gekko the Angeleno leads a tight-knit crew of calamitous creatures. His buddies bound forward, scattering enemies out of the way, with Gekko chasing them down to regroup and go again.",
    one: require("../assets/GEKKO/one.png"),
    oneDescription: "EQUIP Mosh. FIRE to throw Mosh like a grenade. ALT FIRE to lob. Upon landing Mosh duplicates across a large area that deals a small amount of damage over time then after a short delay explodes.",
    two: require("../assets/GEKKO/two.png"),
    twoDescription: "EQUIP Wingman. FIRE to send Wingman forward seeking enemies. Wingman unleashes a Concussive blast toward the first enemy he sees. ALT FIRE when targeting a Spike site or planted Spike to have Wingman defuse or plant the Spike. To plant, Gekko must have the Spike in his inventory.",
    three: require("../assets/GEKKO/three.png"),
    threeDescription: "EQUIP Dizzy. FIRE to send Dizzy soaring forward through the air. Dizzy charges then unleashes plasma blasts at enemies in line of sight. Enemies hit by her plasma are Blinded.",
    ult: require("../assets/GEKKO/ult.png"),
    ultDescription: "EQUIP Thrash. FIRE to link with Thrash's mind and steer her through enemy territory. ACTIVATE to lunge forward and explode, Detaining any players in a small radius.",},
  {
    color:"rgb(19, 157, 243)",
    type: "INITIATOR",
    typeIcon: require("../assets/KAYO/AgentType.png"),
    name: "KAYO",
    emoticon: require("../assets/KAYO/emoticon.png"),
    wallpaper: require("../assets/KAYO/Wallpaper.jpg"),
    description: "KAY/O is a machine of war built for a single purpose: neutralizing radiants. His power to suppress enemy abilities dismantles his opponents' capacity to fight back, securing him and his allies the ultimate edge.",
    one: require("../assets/KAYO/one.png"),
    oneDescription: "EQUIP an explosive fragment. FIRE to throw. ALT FIRE to lob. The fragment sticks to the floor and explodes multiple times, dealing near lethal damage at the center with each explosion.",
    two: require("../assets/KAYO/two.png"),
    twoDescription: "EQUIP a flash grenade. FIRE to overhand throw. ALT FIRE to lob a weaker version that explodes quickly. The flash grenade explodes after a short fuse, Blinding anyone in line of sight.",
    three: require("../assets/KAYO/three.png"),
    threeDescription: "EQUIP a suppression blade. FIRE to throw. The blade sticks to the first surface it hits, winds up, and Suppresses anyone in the radius of the explosion. Enemies can destroy this blade.",
    ult: require("../assets/KAYO/ult.png"),
    ultDescription: "INSTANTLY Overload with polarized radianite energy that pulses from KAY/O in a massive radius. Enemies hit with pulses are Suppressed for a short duration. While overloaded, KAY/O gains Combat Stim and can be re-stabilized if downed.",},
  {
    color:"rgb(13, 255, 0)",
    type: "INITIATOR",
    typeIcon: require("../assets/SKYE/AgentType.png"),
    name: "SKYE",
    emoticon: require("../assets/SKYE/emoticon.png"),
    wallpaper: require("../assets/SKYE/Wallpaper.jpg"),
    description: "Hailing from Australia, Skye and her band of beasts trail-blaze the way through hostile territory. With her creations hampering the enemy, and her power to heal others, the team is strongest and safest by Skye's side.",
    one: require("../assets/SKYE/one.png"),
    oneDescription: "EQUIP a healing trinket. HOLD FIRE to channel, Healing allies in range and line of sight. Can be reused until her healing pool is depleted. Skye cannot heal herself.",
    two: require("../assets/SKYE/two.png"),
    twoDescription: "EQUIP a Tasmanian tiger trinket. FIRE to send out and take control of the predator. While in control, FIRE to leap forward, exploding in a Concussive blast and damaging directly hit enemies.",
    three: require("../assets/SKYE/three.png"),
    threeDescription: "EQUIP a hawk trinket. FIRE to send it forward. HOLD FIRE to guide the hawk in the direction of your crosshair. RE-USE while the hawk is in flight to transform it into a flash. The flash reaches max potency after a short duration during the hawk's flight.",
    ult: require("../assets/SKYE/ult.png"),
    ultDescription: "EQUIP a Seeker trinket. FIRE to send out three Seekers to track down the three closest enemies. If a Seeker reaches its target, it Nearsights them. Enemies can destroy the Seekers.",},
  {
    color:"rgb(5, 154, 196)",
    type: "INITIATOR",
    typeIcon: require("../assets/SOVA/AgentType.png"),
    name: "SOVA",
    emoticon: require("../assets/SOVA/emoticon.png"),
    wallpaper: require("../assets/SOVA/Wallpaper.png"),
    description: "Born from the eternal winter of Russia's tundra, Sova tracks, finds, and eliminates enemies with ruthless efficiency and precision. His custom bow and incredible scouting abilities ensure that even if you run, you cannot hide.",
    one: require("../assets/SOVA/one.png"),
    oneDescription: "EQUIP an owl drone. FIRE to deploy and take control of movement of the drone. While in control of the drone, FIRE to shoot a marking dart. This dart will Reveal the location of any player struck by the dart. Enemies can destroy the Owl Drone.",
    two: require("../assets/SOVA/two.png"),
    twoDescription: "EQUIP a bow with a shock bolt. FIRE to send the explosive bolt forward, detonating upon collision and damaging players nearby. HOLD FIRE to extend the range of the projectile. ALT FIRE to add up to two bounces to this arrow.",
    three: require("../assets/SOVA/three.png"),
    threeDescription: "EQUIP a bow with a recon bolt. FIRE to send the recon bolt forward, activating upon collision and Revealing the location of nearby enemies caught in the line of sight of the bolt. Enemies can destroy this bolt. HOLD FIRE to extend the range of the projectile. ALT FIRE to add up to two bounces to this arrow.",
    ult: require("../assets/SOVA/ult.png"),
    ultDescription: "EQUIP a bow with three long-range, wall-piercing energy blasts. FIRE to release an energy blast in a line in front of Sova, dealing damage and Revealing the location of enemies caught in the line. This ability can be RE-USED up to two more times while the ability timer is active.",},
  {
    color:"rgb(227, 140, 9)",
    type: "INITIATOR",
    typeIcon: require("../assets/TEJO/AgentType.png"),
    name: "TEJO",
    emoticon: require("../assets/TEJO/emoticon.png"),
    wallpaper: require("../assets/TEJO/Wallpaper.png"),
    description: "A veteran intelligence consultant from Colombia, Tejo’s ballistic guidance system pressures the enemy to relinquish their ground - or their lives. His targeted strikes keep opponents off balance and under his heel.",
    one: require("../assets/TEJO/one.png"),
    oneDescription: "EQUIP a stealth drone. FIRE to throw the drone forward, assuming direct control of its movement. FIRE again to trigger a pulse that Suppresses and Reveals enemies hit.",
    two: require("../assets/TEJO/two.png"),
    twoDescription: "EQUIP a sticky grenade. FIRE to launch. The grenade sticks to the first surface it hits and explodes, Concussing any targets caught in the blast. ALT FIRE to launch the grenade with a single bounce instead.",
    three: require("../assets/TEJO/three.png"),
    threeDescription: "EQUIP an AR targeting system. FIRE to select up to two target locations on the map. ALT FIRE to launch missiles that autonomously navigate to target locations, detonating on arrival.",
    ult: require("../assets/TEJO/ult.png"),
    ultDescription: "EQUIP a tactical strike targeting map. FIRE to select the origin point of the strike. FIRE again to set the end point and launch the attack, unleashing a wave of explosions along the strike path. ALT FIRE during map targeting to cancel the origin point.",},
  {
    color:"rgb(183, 0, 255)",
    type: "DUELIST",
    typeIcon: require("../assets/ISO/AgentType.png"),
    name: "ISO",
    emoticon: require("../assets/ISO/emoticon.png"),
    wallpaper: require("../assets/ISO/Wallpaper.png"),
    description: "Chinese fixer for hire Iso goes into a flow state to dismantle the opposition. Reconfiguring ambient energy into bulletproof protection, he advances with focus towards his next duel to the death.",
    one: require("../assets/ISO/one.png"),
    oneDescription: "EQUIP to assemble prismatic energy. FIRE to push an indestructible wall of energy forward that blocks bullets. ALT FIRE to push out a slower version of the wall.",
    two: require("../assets/ISO/two.png"),
    twoDescription: "EQUIP a molecular bolt. Fire to throw it forward, briefly applying Vulnerable & Suppress to all players it touches. The bolt can pass through solid objects, including walls.",
    three: require("../assets/ISO/three.png"),
    threeDescription: "INSTANTLY start channeling your focus. Once focused: gain a shield which absorbs one instance of damage from any source, reload more quickly, and enter a flow state during which downed enemies you kill or damage spawn an energy orb. Shooting this orb refreshes your flow state and your existing shield, or grants another.",
    ult: require("../assets/ISO/ult.png"),
    ultDescription: "EQUIP an interdimensional arena. FIRE to hurl a column of energy through the battlefield, pulling you and the first enemy hit into the arena. You and your opponent duel to the death.",},
  {
    color:"rgb(255, 255, 255)",
    type: "DUELIST",
    typeIcon: require("../assets/JETT/AgentType.png"),
    name: "JETT",
    emoticon: require("../assets/JETT/emoticon.png"),
    wallpaper: require("../assets/JETT/Wallpaper.jpg"),
    description: "Representing her home country of South Korea, Jett's agile and evasive fighting style lets her take risks no one else can. She runs circles around every skirmish, cutting enemies before they even know what hit them.",
    one: require("../assets/JETT/one.png"),
    oneDescription: "INSTANTLY throw a projectile that expands into a brief vision-blocking cloud on impact with a surface. HOLD the ability key to curve the smoke in the direction of your crosshair.",
    two: require("../assets/JETT/two.png"),
    twoDescription: "INSTANTLY propel Jett high into the air.",
    three: require("../assets/JETT/three.png"),
    threeDescription: "ACTIVATE to prepare a gust of wind for a limited time. RE-USE the wind to propel Jett in the direction she is moving. If Jett is standing still, she propels forward. Tailwind charge resets every two kills.",
    ult: require("../assets/JETT/ult.png"),
    ultDescription: "EQUIP a set of highly accurate throwing knives. FIRE to throw a single knife and recharge knives on a kill. ALT FIRE to throw all remaining daggers but does not recharge on a kill.",},
  {
    color:"rgb(4, 131, 216)",
    type: "DUELIST",
    typeIcon: require("../assets/NEON/AgentType.png"),
    name: "NEON",
    emoticon: require("../assets/NEON/emoticon.png"),
    wallpaper: require("../assets/NEON/Wallpaper.jpg"),
    description: "Filipino Agent, Neon, surges forward at shocking speeds, discharging bursts of bioelectric radiance as fast as her body generates it. She races ahead to catch enemies off guard, then strikes them down quicker than lightning.",
    one: require("../assets/NEON/one.png"),
    oneDescription: "FIRE two energy lines forward on the ground that extend a short distance or until they hit a surface. The lines rise into walls of static electricity that block vision.",
    two: require("../assets/NEON/two.png"),
    twoDescription: "INSTANTLY throw an energy bolt that bounces once. Upon hitting each surface, the bolt electrifies the ground below with a Concussive blast.",
    three: require("../assets/NEON/three.png"),
    threeDescription: "INSTANTLY channel Neon's power for Increased Speed. When charged, ALT FIRE to trigger an electric slide dash. Slide charge resets every two kills.",
    ult: require("../assets/NEON/ult.png"),
    ultDescription: "Unleash Neon's full power and speed for a short duration. FIRE to channel the power into a deadly lightning beam with high movement accuracy.",},
  {
    color:"rgb(252, 97, 0)",
    type: "DUELIST",
    typeIcon: require("../assets/PHEONIX/AgentType.png"),
    name: "PHEONIX",
    emoticon: require("../assets/PHEONIX/emoticon.png"),
    wallpaper: require("../assets/PHEONIX/Wallpaper.jpg"),
    description: "Hailing from the U.K., Phoenix's star power shines through in his fighting style, igniting the battlefield with flash and flare. Whether he's got backup or not, he'll rush into a fight on his own terms.",
    one: require("../assets/PHEONIX/one.png"),
    oneDescription: "EQUIP a flame wall. FIRE to create a line of flame that moves forward, passing through the world and creating a wall of fire that blocks vision and damages players passing through it. HOLD FIRE to bend the wall in the direction of your crosshair.",
    two: require("../assets/PHEONIX/two.png"),
    twoDescription: "EQUIP a fireball. FIRE to throw a fireball that explodes after a set amount of time or upon hitting the ground, creating a lingering fire zone that damages enemies. ALT FIRE to lob.",
    three: require("../assets/PHEONIX/three.png"),
    threeDescription: "EQUIP a flare orb that takes a curving path and detonates shortly after throwing. FIRE to curve the flare orb to the left, detonating and Blinding any player who sees the orb. ALT FIRE to curve the flare orb to the right. Curveball resets a charge every two kills.",
    ult: require("../assets/PHEONIX/ult.png"),
    ultDescription: "INSTANTLY place a marker at Phoenix's location. While this ability is active, dying or allowing the timer to expire will end this ability and bring Phoenix back to this location with full health and the amount of armor he had when the ability was cast.",},
  {
    color:"rgb(255, 183, 0)",
    type: "DUELIST",
    typeIcon: require("../assets/RAZE/AgentType.png"),
    name: "RAZE",
    emoticon: require("../assets/RAZE/emoticon.png"),
    wallpaper: require("../assets/RAZE/Wallpaper.jpg"),
    description: "Raze explodes out of Brazil with her big personality and big guns. With her blunt-force-trauma playstyle, she excels at flushing entrenched enemies and clearing tight spaces with a generous dose of “boom.”",
    one: require("../assets/RAZE/one.png"),
    oneDescription: "EQUIP a Boom Bot. FIRE will deploy the bot, causing it to travel in a straight line on the ground, bouncing off walls. The Boom Bot will lock on to any enemies in its frontal cone and chase them, exploding for heavy damage if it reaches them.",
    two: require("../assets/RAZE/two.png"),
    twoDescription: "INSTANTLY throw a Blast Pack that will stick to surfaces. RE-USE the ability after deployment to detonate, damaging and moving anything hit.",
    three: require("../assets/RAZE/three.png"),
    threeDescription: "EQUIP a cluster grenade. FIRE to throw the grenade, which does damage and creates sub-munitions, each doing damage to anyone in their range. ALT FIRE to lob. Paint Shells charge resets every two kills.",
    ult: require("../assets/RAZE/ult.png"),
    ultDescription: "EQUIP a rocket launcher. FIRE to shoot a rocket that does massive area damage on contact with anything.",},
  {
    color:"rgba(164, 6, 135, 0.73)",
    type: "DUELIST",
    typeIcon: require("../assets/REYNA/AgentType.png"),
    name: "REYNA",
    emoticon: require("../assets/REYNA/emoticon.png"),
    wallpaper: require("../assets/REYNA/Wallpaper.jpg"),
    description: "Forged in the heart of Mexico, Reyna dominates single combat, popping off with each kill she scores. Her capability is only limited by her raw skill, making her highly dependent on performance.",
    one: require("../assets/REYNA/one.png"),
    oneDescription: "EQUIP an ethereal, destructible eye. ACTIVATE to cast the eye a short distance forward. The eye will Nearsight all enemies who look at it.",
    two: require("../assets/REYNA/two.png"),
    twoDescription: "INSTANTLY consume a nearby soul orb, rapidly Healing. If  Empress is active, this skill will automatically cast and not consume the Soul Orb.",
    three: require("../assets/REYNA/three.png"),
    threeDescription: "INSTANTLY consume a nearby Soul Orb, becoming Intangible for a short duration. If  Empress is active, also become Invisible.",
    ult: require("../assets/REYNA/ult.png"),
    ultDescription: "INSTANTLY enter a frenzy, gaining a Combat Stim that increases firing, equip and reload speed dramatically. Gain infinite charges of Soul Harvest abilities.",},
  {
    color:"rgba(1, 11, 199, 0.74)",
    type: "DUELIST",
    typeIcon: require("../assets/YORU/AgentType.png"),
    name: "YORU",
    emoticon: require("../assets/YORU/emoticon.png"),
    wallpaper: require("../assets/YORU/Wallpaper.jpg"),
    description: "Japanese native Yoru rips holes straight through reality to infiltrate enemy lines unseen. Using deception and aggression in equal measure, he gets the drop on each target before they know where to look.",
    one: require("../assets/YORU/one.png"),
    oneDescription: "EQUIP an echo that transforms into a mirror image of Yoru when activated. FIRE to instantly activate the mirror image and send it forward. ALT FIRE to place an inactive echo. USE to transform an inactive echo into a mirror image and send it forward. Mirror images explode in a Blinding Flash when destroyed by enemies.",
    two: require("../assets/YORU/two.png"),
    twoDescription: "EQUIP to rip an unstable dimensional fragment from reality. FIRE to throw the fragment, activating a flash that winds up once it collides with a hard surface.",
    three: require("../assets/YORU/three.png"),
    threeDescription: "EQUIP a rift tether. FIRE to send the tether forward. ALT FIRE to place a stationary tether. ACTIVATE to teleport to the tether's location. USE to trigger a fake teleport. GATECRASH resets a charge every two kills.",
    ult: require("../assets/YORU/ult.png"),
    ultDescription: "EQUIP a mask that can see between dimensions. FIRE to drift into Yoru's dimension, unable to be affected or seen by enemies from the outside. REACTIVATE to exit Yoru's dimension early.",},
  {
    color:"rgb(206, 172, 37)",
    type: "SENTINAL",
    typeIcon: require("../assets/CHAMBER/AgentType.png"),
    name: "CHAMBER",
    emoticon: require("../assets/CHAMBER/emoticon.png"),
    wallpaper: require("../assets/CHAMBER/Wallpaper.jpg"),
    description: "Well-dressed and well-armed, French weapons designer Chamber expels aggressors with deadly precision. He leverages his custom arsenal to hold the line and pick off enemies from afar, with a contingency built for every plan.",
    one: require("../assets/CHAMBER/one.png"),
    oneDescription: "EQUIP a trap that scans for enemies. FIRE to place it on the ground. When a visible enemy comes in range, the trap counts down and then destabilizes the terrain around them, creating a lingering field that Slows players caught inside of it. The trap can be picked up to be REDEPLOYED.",
    two: require("../assets/CHAMBER/two.png"),
    twoDescription: "ACTIVATE to equip a heavy pistol. ALT FIRE with the pistol equipped to aim down sights.",
    three: require("../assets/CHAMBER/three.png"),
    threeDescription: "EQUIP a teleport anchor. FIRE to place it on the ground. While on the ground and in range of the anchor, REACTIVATE to quickly teleport to the anchor. The anchor can be picked up to be REDEPLOYED.",
    ult: require("../assets/CHAMBER/ult.png"),
    ultDescription: "ACTIVATE to summon a powerful, custom sniper rifle that will kill an enemy with any direct hit to the upper body. ALT FIRE to aim down sights. Killing an enemy creates a lingering field that Slows players caught inside of it.",},
  {
    color:"rgb(101, 205, 212)",
    type: "SENTINAL",
    typeIcon: require("../assets/CYPHER/AgentType.png"),
    name: "CYPHER",
    emoticon: require("../assets/CYPHER/emoticon.png"),
    wallpaper: require("../assets/CYPHER/Wallpaper.jpg"),
    description: "The Moroccan information broker, Cypher is a one-man surveillance network who keeps tabs on the enemy’s every move. No secret is safe. No maneuver goes unseen. Cypher is always watching.",
    one: require("../assets/CYPHER/one.png"),
    oneDescription: "EQUIP a trapwire. FIRE to place a destructible and covert trapwire at the targeted location, creating a line that spans between the placed location and the wall opposite. Enemy players who cross a trapwire will be Tethered, Revealed, and Concussed after a short period if they do not destroy the device in time. This ability can be picked up to be REDEPLOYED.",
    two: require("../assets/CYPHER/two.png"),
    twoDescription: "INSTANTLY toss the cyber cage in front of Cypher. ACTIVATE to create a zone that blocks vision and plays an audio cue when enemies pass through it.",
    three: require("../assets/CYPHER/three.png"),
    threeDescription: "EQUIP a spycam. FIRE to place the spycam at the targeted location. RE-USE this ability to take control of the camera's view. While in control of the camera, FIRE to shoot a marking dart. This dart will Reveal the location of any player struck by the dart. This ability can be picked up to be REDEPLOYED.",
    ult: require("../assets/CYPHER/ult.png"),
    ultDescription: "INSTANTLY use on a targeted dead enemy to download information on their team. After a brief delay, the location of all living enemy players will be Revealed twice.",},
  {
    color:"rgb(9, 107, 152)",
    type: "SENTINAL",
    typeIcon: require("../assets/DEADLOCK/AgentType.png"),
    name: "DEADLOCK",
    emoticon: require("../assets/DEADLOCK/emoticon.png"),
    wallpaper: require("../assets/DEADLOCK/Wallpaper.png"),
    description: "Norwegian operative Deadlock deploys an array of cutting-edge nanowire to secure the battlefield from even the most lethal assault. No one escapes her vigilant watch, nor survives her unyielding ferocity.",
    one: require("../assets/DEADLOCK/one.png"),
    oneDescription: "EQUIP a Barrier Mesh disc. FIRE to throw forward. Upon landing, the disc generates barriers from the origin point that block character movement.",
    two: require("../assets/DEADLOCK/two.png"),
    twoDescription: "EQUIP a Sonic Sensor. FIRE to deploy. The sensor monitors an area for enemies making sound. It concusses that area if footsteps, weapons fire, or significant noise are detected. This ability can be picked up to be REDEPLOYED.",
    three: require("../assets/DEADLOCK/three.png"),
    threeDescription: "EQUIP a GravNet grenade. FIRE to throw. ALT FIRE to lob. The GravNet detonates upon landing, forcing any characters caught within to crouch and move slowly.",
    ult: require("../assets/DEADLOCK/ult.png"),
    ultDescription: "EQUIP a Nanowire Accelerator. FIRE to unleash a pulse of nanowires that captures the first enemy contacted. The cocooned enemy is pulled along a nanowire path and will die unless they are freed. The nanowire cocoon is destructible.",},
  {
    color:"rgb(240, 243, 48)",
    type: "SENTINAL",
    typeIcon: require("../assets/KILLJOY/AgentType.png"),
    name: "KILLJOY",
    emoticon: require("../assets/KILLJOY/emoticon.png"),
    wallpaper: require("../assets/KILLJOY/Wallpaper.jpg"),
    description: "The genius of Germany, Killjoy effortlessly secures key battlefield positions with her arsenal of inventions. If their damage doesn't take her enemies out, the debuff her robots provide will make short work of them.",
    one: require("../assets/KILLJOY/one.png"),
    oneDescription: "EQUIP a covert Alarmbot. FIRE to deploy a bot that hunts down enemies that get in range. After reaching its target, the bot explodes and applies Vulnerable to enemies in the area. HOLD EQUIP to recall a deployed bot.",
    two: require("../assets/KILLJOY/two.png"),
    twoDescription: "EQUIP a Nanoswarm grenade. FIRE to throw the grenade. Upon landing, the Nanoswarm goes covert. ALT FIRE to lob. ACTIVATE the Nanoswarm to deploy a damaging swarm of nanobots.",
    three: require("../assets/KILLJOY/three.png"),
    threeDescription: "EQUIP a Turret. FIRE to deploy a turret that fires at enemies in a 100 degree cone. ALT FIRE to swap turret direction. HOLD EQUIP to recall the deployed turret.",
    ult: require("../assets/KILLJOY/ult.png"),
    ultDescription: "EQUIP the Lockdown device. FIRE to deploy the device. After a long windup, the device Detains all enemies caught in the radius. The device can be destroyed by enemies.",},
  {
    color:"rgb(9, 227, 176)",
    type: "SENTINAL",
    typeIcon: require("../assets/SAGE/AgentType.png"),
    name: "SAGE",
    emoticon: require("../assets/SAGE/emoticon.png"),
    wallpaper: require("../assets/SAGE/Wallpaper.jpg"),
    description: "The bastion of China, Sage creates safety for herself and her team wherever she goes. Able to revive fallen friends and stave off aggressive pushes, she provides a calm center to a hellish fight.",
    one: require("../assets/SAGE/one.png"),
    oneDescription: "EQUIP a barrier orb. FIRE places a wall that fortifies after a few seconds. ALT FIRE rotates the targeter.",
    two: require("../assets/SAGE/two.png"),
    twoDescription: "EQUIP a slowing orb. FIRE to throw a slowing orb forward that detonates upon landing, creating a lingering field that Slows and reduces the dash speed of players caught inside of it.",
    three: require("../assets/SAGE/three.png"),
    threeDescription: "EQUIP a healing orb. FIRE with your crosshairs over a damaged ally to activate a Heal-Over-Time on them. ALT FIRE while Sage is damaged to activate a self Heal-Over-Time.",
    ult: require("../assets/SAGE/ult.png"),
    ultDescription: "EQUIP a resurrection ability. FIRE with your crosshairs placed over a dead ally to begin resurrecting them. After a brief channel, the ally will be brought back to life with full health.",},
  {
    color:"rgba(73, 11, 84, 0.71)",
    type: "SENTINAL",
    typeIcon: require("../assets/VYSE/AgentType.png"),
    name: "VYSE",
    emoticon: require("../assets/VYSE/emoticon.png"),
    wallpaper: require("../assets/VYSE/Wallpaper.png"),
    description: "Metallic mastermind Vyse unleashes liquid metal to isolate, trap, and disarm her enemies. Through cunning and manipulation, she forces all who oppose her to fear the battlefield itself.",
    one: require("../assets/VYSE/one.png"),
    oneDescription: "EQUIP filaments of liquid metal. FIRE to place a hidden wall trap. When an enemy crosses, an indestructible wall bursts from the ground behind them. The wall lasts for a brief time before dissipating.",
    two: require("../assets/VYSE/two.png"),
    twoDescription: "EQUIP a nest of liquid metal. FIRE to launch. Upon landing, the nest becomes invisible. When ACTIVATED, it sprawls out into a large razorvine nest which slows and damages all players who move through it.",
    three: require("../assets/VYSE/three.png"),
    threeDescription: "EQUIP an Arc Rose. Target a surface and FIRE to place a stealthed Arc Rose, or ALT FIRE to place the Arc Rose through it. REUSE to blind all players looking at it. This ability can be picked up to be REDEPLOYED.",
    ult: require("../assets/VYSE/ult.png"),
    ultDescription: "EQUIP a bramble of liquid metal. FIRE to send the metal erupting from you as a torrent of metal thorns, JAMMING enemy primary weapons after a brief windup.",},
];
