//sample data
export const people = [
    { name: 'divyansh sinha', age: 21, gender: 'male' },
    { name: 'shashank chandra', age: 22, gender: 'male' },
    { name: 'ayush kumar', age: 23, gender: 'male' },
    { name: 'omar khan', age: 22, gender: 'male' },
    { name: 'rahul verma', age: 24, gender: 'male' },
    { name: 'manish sharma', age: 21, gender: 'male' },
    { name: 'aditya mehta', age: 25, gender: 'male' },
    { name: 'rohit singh', age: 23, gender: 'male' },
    { name: 'vikas yadav', age: 22, gender: 'male' },
    { name: 'ankit raj', age: 24, gender: 'male' },
    { name: 'harsh tiwari', age: 21, gender: 'male' },
    { name: 'deepak chauhan', age: 23, gender: 'male' },
    { name: 'saurabh pandey', age: 22, gender: 'male' },
    { name: 'kunal joshi', age: 25, gender: 'male' },
    { name: 'prateek saxena', age: 24, gender: 'male' },
    { name: 'rajat mishra', age: 23, gender: 'male' },
    { name: 'nishant rana', age: 22, gender: 'male' },
    { name: 'mayank bhatt', age: 21, gender: 'male' },
    { name: 'tushar kapoor', age: 23, gender: 'male' },
    { name: 'yash raj', age: 24, gender: 'male' },
    { name: 'arjun rawat', age: 22, gender: 'male' },
    { name: 'karan malik', age: 23, gender: 'male' },
    { name: 'himanshu singh', age: 25, gender: 'male' },
    { name: 'abhinav jha', age: 21, gender: 'male' },
    { name: 'alok nath', age: 24, gender: 'male' },
    { name: 'sanket joshi', age: 23, gender: 'male' },
    { name: 'shubham patel', age: 22, gender: 'male' },
    { name: 'anurag saxena', age: 21, gender: 'male' },
    { name: 'piyush gupta', age: 24, gender: 'male' },
    { name: 'bhanu pratap', age: 23, gender: 'male' }
  ];